openedx/openedx-k8s-harmony

catalog-info.yaml
This PR adds the catalog file to be read by backstage.
It makes the `tutor-contrib-multi` group the official maintainer of this repo.
I took the group from 
https://github.com/openedx/tcril-engineering/issues/577
However I can't tag this group. Maybe it is private. Also the group will change once the name of the project changes.
I'll update this PR once that happens.
=> chore: adding the catalog file for backstage

.gitignore, README.md, infra-example/k8s-cluster/main.tf, tutor-contrib-multi-plugin/tutor_multi_k8s_plugin/commands.py, tutor-contrib-multi-plugin/tutor_multi_k8s_plugin/elasticsearch.py, tutor-contrib-multi-plugin/tutor_multi_k8s_plugin/patches/k8s-services, tutor-contrib-multi-plugin/tutor_multi_k8s_plugin/patches/openedx-common-settings, tutor-contrib-multi-plugin/tutor_multi_k8s_plugin/patches/openedx-dockerfile-post-python-requirements, tutor-contrib-multi-plugin/tutor_multi_k8s_plugin/plugin.py, tutor-multi-chart/Chart.lock, tutor-multi-chart/Chart.yaml, tutor-multi-chart/templates/elasticsearch/secrets.yaml, tutor-multi-chart/values.yaml, values-example.yaml
This PR adds the helm chart to deploy a standalone Elasticsearch cluster. Ref overhangio/tutor-forum#4 
When `elasticsearch.enabled` is true it will deploy a cluster with 3 replicas by default.
Operators will need to add/update the following setting in each of their instances. 
```yaml
K8S_HARMONY_ENABLE_SHARED_ELASTICSEARCH: true
RUN_ELASTICSEARCH: false
```
- In order for SSL to work without warnings the CA certificate needs to be mounted in the relevant pods. This is out of scope for this PR as it needs to be an instance level change, which requires more work than intended.
- It's not possible to mount the CA certificate for the forum due to https://github.com/overhangio/tutor/issues/791
- Follow the instructions to install the chart and rebuild the Open edX image (`tutor image build …
=> feat: shared elasticsearch

.github/workflows/release.yml
This PR aims to fix an issue during the Harmony chart release (check this [failed release](https://github.com/openedx/openedx-k8s-harmony/actions/runs/7096528812/job/19315183193) ). The `helm repo` subcommands are not supported for OCI registries. See https://helm.sh/docs/topics/registries/ to get more details.
It was tested in this [fork](https://github.com/eduNEXT/openedx-k8s-harmony) where the release was generated with success
=> fix: bypassing OCI registries for Harmony chart release

charts/harmony-chart/Chart.lock, charts/harmony-chart/Chart.yaml, charts/harmony-chart/templates/NOTES.txt, charts/harmony-chart/templates/echo.yaml, charts/harmony-chart/values.yaml, values-example.yaml, values-minikube.yaml
This PR adds the prometheus-stack Helm chart as a dependency to monitor the cluster, closing #37 and #38. The stack is crafted by [Prometheus](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack).
The default values are disabling Prometheus _and_ Grafana, so if one only needs Prometheus but not Grafana, no extra steps are necessary.
An example configuration for the chart (by the end user) could be
```yaml
prometheusstack:
enabled: true
grafana:
enabled: true
ingress:
enabled: true
ingressClassName: nginx
annotations:
cert-manager.io/cluster-issuer: "harmony-letsencrypt-global"
nginx.ingress.kubernetes.io/ssl-redirect: "true"
hosts:
- grafana.example.com
tls:
- secretName: promstack-ingress-tls
hosts:
- grafana.example.com
```
1. Setup a K8s cluster …
=> Add monitoring using prometheus-stack

charts/harmony-chart/Chart.lock, charts/harmony-chart/Chart.yaml, charts/harmony-chart/templates/NOTES.txt, charts/harmony-chart/templates/issuer.yaml, charts/harmony-chart/values.yaml, values-example.yaml, values-minikube.yaml
This PR resolves https://github.com/openedx/openedx-k8s-harmony/issues/52 by adding K8s dashboard to the charts. The chart is enabled by default to avoid extra resource installations.
I made some smaller adjustments like bumping the cert issues and fixing a wrong doc string.
=> feat: add kubernetes dashboard

charts/harmony-chart/Chart.yaml, charts/harmony-chart/templates/NOTES.txt
The NOTES.txt currently missing a closing `end` for an `if` statement in the Go template, making it broken and preventing the helm chart to be installed. This PR adds the missing `{{ end }}` to close the initial `{{ if and .Values.prometheusstack.grafana.enabled ... }}` statement.
To check the issue, run the following: https://go.dev/play/p/dakeHH1Mrq5
Then to check the fix: https://go.dev/play/p/APXiGU29pci
The difference between the two is the above-mentioned closing tag.
=> fix: add missing end-if in notes.txt

charts/harmony-chart/Chart.lock, charts/harmony-chart/Chart.yaml, charts/harmony-chart/values.yaml, values-example.yaml
This PR adds optional Velero backups to backup the cluster resources. The backup location can be any S3-compatible storage.
Velero requires CRD installation before enabled, just as the Cert manager. Since we have no dedicated documentation page for the optional resources, I made a note about it in the value examples.
=> Add optional Velero chart

charts/harmony-chart/Chart.lock, charts/harmony-chart/Chart.yaml, charts/harmony-chart/templates/NOTES.txt, charts/harmony-chart/templates/openfaas/namespace.yaml, charts/harmony-chart/values.yaml, values-example.yaml, values-minikube.yaml
This PR resolves #53 by adding an optional OpenFAAS chart to the dependencies.
Example configuration:
```
openfaas:
enabled: true
ingress:
enabled: false
hosts:
- host: gateway.openfaas.local  # Replace with gateway.example.com if public-facing
serviceName: gateway
servicePort: 8080
path: /
annotations:
kubernetes.io/ingress.class: nginx
cert-manager.io/cluster-issuer: letsencrypt-prod
nginx.ingress.kubernetes.io/ssl-redirect: "true" 
nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
```
=> Add optional OpenFAAS chart

README.md, infra-examples/aws/README.md, infra-examples/aws/k8s-cluster/main.tf, infra-examples/aws/vpc/main.tf, infra-examples/digitalocean/main.tf
This PR replaces Terraform with Open Tofu where it makes sense due to the license changes on Terraform's side. The PR, however, is not replacing any references to the Terraform registry. Also, it is not replacing “Terraform”, where the module name includes Terraform as well (like the AWS EKS Terraform Module).
=> Replace Terraform with OpenTofu

charts/harmony-chart/Chart.lock, charts/harmony-chart/Chart.yaml
This PR bumps the harmony chart version to indicate that the chart supports Tutor 17.x (v17.0.4).
=> chore: bump harmony chart version

charts/harmony-chart/templates/elasticsearch/secrets.yaml
The generated ES self-signed certificate is using an old name of the ES cluster, therefore it cannot be validated. This PR updates the ES cluster name defined in the certificate, so it can be validated, even it is self-signed.
=> fix: ensure ES cluster cert name is valid

tutor-contrib-harmony-plugin/tutor_k8s_harmony_plugin/patches/k8s-services, tutor-contrib-harmony-plugin/tutor_k8s_harmony_plugin/plugin.py
This PR adds the Discovery and Ecommerce hosts to the ingress configuration if the corresponding variables are defined.
- Deploy instance
- Setup discovery
- Setup ecommerce (optional as both services are configured the same way)
- Check that discovery loads
=> refactor: extend ingress hosts

tutor-contrib-harmony-plugin/tutor_k8s_harmony_plugin/patches/k8s-services
Tutor [uses](https://github.com/overhangio/tutor/blob/01d078c28413b7015b81f831934a7720bb668091/tutor/templates/config/defaults.yml#L71) `PREVIEW_LMS_HOST`, thus this fix.
=> fix: typo PREVIEW_HOST -> PREVIEW_LMS_HOST

tutor-contrib-harmony-plugin/setup.py
(edit by @gabor-boros):
This PR bumping the required tutor versions to support Redwood. It has been tested that harmony supports Redwood.
=> chore: bump tutor plugin dependency version for redwood support

charts/harmony-chart/Chart.yaml
This PR simply bumps chart version and application version to indicate it supports Redwood.
=> chore: bump chart to indicate app version update

.github/workflows/renovate.yaml, renovate.json
This PR implements the renovate bot to update helm Chart dependencies.
It was run with a temporal Personal Access Token on a fork. See https://github.com/eduNEXT/openedx-k8s-harmony/pulls for details of the PRs. Here is the log of a successful run: https://github.com/eduNEXT/openedx-k8s-harmony/actions/runs/11521490246/job/32075754011
The upgrades will be easily tested once #80 is merged
frontend-app-authoring already uses [renovate](https://github.com/openedx/frontend-app-authoring/blob/master/renovate.json) to upgrade npm packages.
=> build: add renovate bot

charts/harmony-chart/Chart.lock, charts/harmony-chart/Chart.yaml, charts/harmony-chart/templates/issuer.yaml
This PR upgrades the helm chart dependencies to the latest version.
Cert manager cannot be upgraded to v1.16 because of this bug: https://github.com/cert-manager/cert-manager/issues/1829
The upgrade was already tested on a production k8s cluster by upgrading from the current version to the new one.
=> chore(bump): upgrade helm chart global dependencies

charts/harmony-chart/Chart.lock, charts/harmony-chart/Chart.yaml, charts/harmony-chart/values.yaml, values-example.yaml
This PR adds Vector as a dependency and sets defaults for:
- Extracting application logs (lms, cms, ingress, cert-manager, etc)
- Extracting tracking logs from Open edX.
- Storing compressed tracking logs in `gzip` files on an S3-like storage (can be tweaked to work with Cloudwatch, Minio, etc)  by date.
Closes: #32
=> feat: add vector with defaults

charts/harmony-chart/Chart.yaml, charts/harmony-chart/values.yaml
The cert-manager validations are strict so it won't accept un-supported values in the chart configuration. This PR removes the `email` (it is not supported in the current chart version) value from the cert-manager configuration to prevent failures in installing the Harmony chart.
=> fix: removing cert-manager invalid value

charts/harmony-chart/Chart.yaml, charts/harmony-chart/templates/echo.yaml, charts/harmony-chart/templates/elasticsearch/secrets.yaml, charts/harmony-chart/templates/opensearch/secrets.yaml
In the Harmony Chart templates, there are resources whose existence must be conditioned to the activation/deactivation of a specific subchart. In this PR conditionals are added to create specific resources only when the related subchart is enabled
=> fix: adding resources only if right subcharts are enabled

charts/harmony-chart/templates/issuer.yaml, charts/harmony-chart/values.yaml
This PR is supposed to fix the removal of `email` field from the `cert-manager` key. More info: https://github.com/openedx/openedx-k8s-harmony/pull/126#issuecomment-2547688485
=> fix: ensure let's encrypt email can be set

charts/harmony-chart/Chart.lock, charts/harmony-chart/Chart.yaml
This PR bumps the ingress-nginx chart version due to a vulnerability in the current chart.
=> chore: bump ingress-nginx and format file

tutor-contrib-harmony-plugin/tutor_k8s_harmony_plugin/patches/k8s-services
MEILISEARCH_HOST is introduced so that we can add it to the ingress controller
**Discussions**: [Slack Discussion](https://openedx.slack.com/archives/C05519HHZKM/p1739341680191669?thread_ts=1739257428.215229&cid=C05519HHZKM)
**Dependencies**: None
~~**Screenshots**: Always include screenshots if there is any change to the UI.~~
**Testing instructions**:
None
Private ref: [BB-9563](https://tasks.opencraft.com/browse/BB-9563)
REF: https://github.com/overhangio/tutor/pull/1209
=> Adds MEILISEARCH_HOST to ingress.

README.md, tutor-contrib-harmony-plugin/tutor_k8s_harmony_plugin/patches/caddyfile
Hi all,
I would like to propose this addition.
Multi-site K8s deployments might benefit from having one single Meilisearch server, installed out of the K8s cluster (which I would recommend). 
However, the [ingress will direct](https://github.com/openedx/openedx-k8s-harmony/blob/8fca56794114a9bc460de9a982c756d0215de6a8/tutor-contrib-harmony-plugin/tutor_k8s_harmony_plugin/patches/k8s-services#L11) the MAILISEARCH_HOST to Caddy.
In this case a proxy for each site to the server might be useful.
=> feat: Add proxy for meilisearch host when ran out of the cluster.
